version: '3'

services:
  lms-iac:
    container_name: boilerplate-nextjs
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8094:3000
    env_file:
      - .env.production